require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Ottrick
  RSpec.describe OtrsQueuesController, :type => :controller do
  routes { Ottrick::Engine.routes }

    # This should return the minimal set of attributes required to create a valid
    # OtrsQueue. As you add validations to OtrsQueue, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      { name: "Test", otrs_queue_id: 3 }
    }

    let(:invalid_attributes) {
      {quark: "dummy" }
    }

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # OtrsQueuesController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe "GET index" do
      it "assigns all otrs_queues as @otrs_queues" do
        otrs_queue = OtrsQueue.create! valid_attributes
        get :index, {}, valid_session
        expect(assigns(:otrs_queues)).to eq([otrs_queue])
      end
    end

    describe "GET show" do
      it "assigns the requested otrs_queue as @otrs_queue" do
        otrs_queue = OtrsQueue.create! valid_attributes
        get :show, {:id => otrs_queue.to_param}, valid_session
        expect(assigns(:otrs_queue)).to eq(otrs_queue)
      end
    end

    describe "GET new" do
      it "assigns a new otrs_queue as @otrs_queue" do
        get :new, {}, valid_session
        expect(assigns(:otrs_queue)).to be_a_new(OtrsQueue)
      end
    end

    describe "GET edit" do
      it "assigns the requested otrs_queue as @otrs_queue" do
        otrs_queue = OtrsQueue.create! valid_attributes
        get :edit, {:id => otrs_queue.to_param}, valid_session
        expect(assigns(:otrs_queue)).to eq(otrs_queue)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new OtrsQueue" do
          expect {
            post :create, {:otrs_queue => valid_attributes}, valid_session
          }.to change(OtrsQueue, :count).by(1)
        end

        it "assigns a newly created otrs_queue as @otrs_queue" do
          post :create, {:otrs_queue => valid_attributes}, valid_session
          expect(assigns(:otrs_queue)).to be_a(OtrsQueue)
          expect(assigns(:otrs_queue)).to be_persisted
        end

        it "redirects to the created otrs_queue" do
          post :create, {:otrs_queue => valid_attributes}, valid_session
          expect(response).to redirect_to(OtrsQueue.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved otrs_queue as @otrs_queue" do
          post :create, {:otrs_queue => invalid_attributes}, valid_session
          expect(assigns(:otrs_queue)).to be_a_new(OtrsQueue)
        end

        it "re-renders the 'new' template" do
          post :create, {:otrs_queue => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested otrs_queue" do
          otrs_queue = OtrsQueue.create! valid_attributes
          put :update, {:id => otrs_queue.to_param, :otrs_queue => new_attributes}, valid_session
          otrs_queue.reload
          skip("Add assertions for updated state")
        end

        it "assigns the requested otrs_queue as @otrs_queue" do
          otrs_queue = OtrsQueue.create! valid_attributes
          put :update, {:id => otrs_queue.to_param, :otrs_queue => valid_attributes}, valid_session
          expect(assigns(:otrs_queue)).to eq(otrs_queue)
        end

        it "redirects to the otrs_queue" do
          otrs_queue = OtrsQueue.create! valid_attributes
          put :update, {:id => otrs_queue.to_param, :otrs_queue => valid_attributes}, valid_session
          expect(response).to redirect_to(otrs_queue)
        end
      end

      describe "with invalid params" do
        it "assigns the otrs_queue as @otrs_queue" do
          otrs_queue = OtrsQueue.create! valid_attributes
          put :update, {:id => otrs_queue.to_param, :otrs_queue => invalid_attributes}, valid_session
          expect(assigns(:otrs_queue)).to eq(otrs_queue)
        end

        it "re-renders the 'edit' template" do
          pending "example does not work, reason unknown"
          otrs_queue = OtrsQueue.create! valid_attributes
          put :update, {:id => otrs_queue.to_param, :otrs_queue => invalid_attributes}, valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested otrs_queue" do
        otrs_queue = OtrsQueue.create! valid_attributes
        expect {
          delete :destroy, {:id => otrs_queue.to_param}, valid_session
        }.to change(OtrsQueue, :count).by(-1)
      end

      it "redirects to the otrs_queues list" do
        otrs_queue = OtrsQueue.create! valid_attributes
        delete :destroy, {:id => otrs_queue.to_param}, valid_session
        expect(response).to redirect_to(otrs_queues_url)
      end
    end

  end
end
